Repository Pale-Blue-Dot-97/Minerva, pull requests merged in 2023-07, with the labels that each got.

#191 Document notebooks
  .pre-commit-config.yaml
  README.md
  notebooks/Torchgeo_FCN_Demo.ipynb
  notebooks/Torchgeo_FCN_Full.ipynb
  notebooks/Torchgeo_FCN_Small.ipynb
  notebooks/Visualise_Siamese_Pair.ipynb
Labels: bug, documentation, boilerplate

#189 Clean up tests
  Pipfile
  Pipfile.lock
  minerva/utils/utils.py
  minerva/utils/visutils.py
  pyproject.toml
  requirements/requirements_dev.txt
  setup.cfg
  tests/conftest.py
  tests/test_datasets.py
  tests/test_trainer.py
  tests/test_transforms.py
  tests/test_utils.py
Labels: boilerplate, dependencies, testing, type hinting

#192 Minerva v0.25
  .pre-commit-config.yaml
  MANIFEST.in
  Pipfile
  Pipfile.lock
  README.md
  banner.txt
  docs/docs_readme.md
  minerva/datasets.py
  minerva/inbuilt_cfgs/example_3rd_party.yml
  minerva/inbuilt_cfgs/example_CNN_config.yml
  minerva/inbuilt_cfgs/example_GeoCLR_config.yml
  minerva/inbuilt_cfgs/example_UNetR_config.yml
  minerva/inbuilt_cfgs/example_autoencoder_config.yml
  minerva/inbuilt_cfgs/example_config.yml
  minerva/trainer.py
  minerva/utils/utils.py
  minerva/utils/visutils.py
  notebooks/Torchgeo_FCN_Demo.ipynb
  notebooks/Torchgeo_FCN_Full.ipynb
  notebooks/Torchgeo_FCN_Small.ipynb
  notebooks/Visualise_Siamese_Pair.ipynb
  pyproject.toml
  requirements/requirements_dev.txt
  setup.cfg
  tests/conftest.py
  tests/test_datasets.py
  tests/test_trainer.py
  tests/test_transforms.py
  tests/test_utils.py
Labels: bug, documentation, enhancement, generalise, boilerplate, dependencies, testing, restructure, type hinting, formatting

#194 Return a PairedUnionDataset when joining to one
  minerva/datasets.py
  tests/test_datasets.py
Labels: bug
